name: icnn4opt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - tensorflow
  - ipopt
  - jupyterlab
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - pip
  - pip:
      - cvxpy
      - pyomo
      - pypower
      - pandapower